export const USER_PREFERENCE_REPOSITORY = Symbol('USER_PREFERENCE_REPOSITORY');
export const PRODUCT_REPOSITORY = Symbol('PRODUCT_REPOSITORY');
export const PRODUCT_COMPONENT_REPOSITORY = Symbol('PRODUCT_COMPONENT_REPOSITORY');
export const SELLER_OFFER_REPOSITORY = Symbol('SELLER_OFFER_REPOSITORY');
export const PRICE_HISTORY_REPOSITORY = Symbol('PRICE_HISTORY_REPOSITORY');
export const ANALYSIS_REPOSITORY = Symbol('ANALYSIS_REPOSITORY');
export const SAVED_PRODUCT_REPOSITORY = Symbol('SAVED_PRODUCT_REPOSITORY');
export const PRICE_ALERT_REPOSITORY = Symbol('PRICE_ALERT_REPOSITORY');
