steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=Dockerfile
      - --tag=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/backend:${_TAG}
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=agent/Dockerfile
      - --tag=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/agent:${_TAG}
      - agent
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=core/Dockerfile
      - --tag=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/core:${_TAG}
      - core
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=frontend/a/Dockerfile
      - --tag=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/web:${_TAG}
      - frontend/a
images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/backend:${_TAG}
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/agent:${_TAG}
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/core:${_TAG}
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/web:${_TAG}
substitutions:
  _REGION: us-central1
  _REPOSITORY: catchcatch
  _TAG: latest
options:
  logging: CLOUD_LOGGING_ONLY

